import { KOL, ContentItem, IP, Brand, WeeklyBrief, CalendarEvent } from "@/types";
import type { Country, Language, Emotion } from "@/types";

export const countryLabel: Record<Country, string> = {
  US: "美国", UK: "英国", AU: "澳洲", SG: "新加坡", MY: "马来西亚", TH: "泰国", ID: "印尼",
  PH: "菲律宾", VN: "越南", JP: "日本", KR: "韩国", FR: "法国", DE: "德国", CA: "加拿大", CN: "中国",
};
export const languageLabel: Record<Language, string> = {
  en: "English", zh: "中文", ja: "日本語", ko: "한국어", th: "ไทย", id: "Bahasa Indonesia",
  vi: "Tiếng Việt", tl: "Tagalog", ms: "Bahasa Melayu", fr: "Français", de: "Deutsch", es: "Español",
};
export const emotionLabel: Record<Emotion, string> = {
  joy: "愉悦", calm: "宁静", humor: "幽默", nostalgia: "怀旧", excitement: "兴奋", empathy: "共情", awe: "惊叹", curiosity: "好奇",
};

export const defaultBrand: Brand = {
  id: "chagee-001",
  name: "CHAGEE",
  category: "新中式茶饮",
  priceTier: "Premium",
  visualStyle: ["Oriental Aesthetic", "Modern", "Minimalist"],
  markets: ["US", "UK", "SEA"],
  targetAudiences: [
    {
      id: "ta-1",
      name: "新中产女性核心群",
      ageRange: [22, 35],
      gender: "female",
      interests: ["茶文化", "东方美学", "wellness", "lifestyle", "fashion", "travel"],
    },
    {
      id: "ta-2",
      name: "文化认同年轻群",
      ageRange: [18, 28],
      gender: "all",
      interests: ["anime", "K-pop", "streetwear", "Asian culture", "aesthetic", "Genshin Impact"],
    },
  ],
};

export const trends: ContentItem[] = [
  {
    id: "t1",
    platform: "tiktok",
    title: "Soft Life Aesthetic",
    description: "柔和色调、慢节奏生活的短视频风格在TikTok快速蔓延，尤其受18-24岁女性追捧。核心元素：奶油色系视觉、ASMR音效、慢动作倒饮镜头。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 340000000, likes: 28000000, shares: 5200000, comments: 1800000, growthRate: 26, heatScore: 0 },
    format: "audio",
    tags: ["SoftLife", "aesthetic", "cozyvibes", "slowliving"],
    country: "US",
    language: "en",
    emotion: "calm",
    demographicAffinity: { age_18_24: 0.78, age_25_34: 0.15, age_35_44: 0.05, female: 0.82, male: 0.18 },
    audienceOverlap: 92,
    lifecycle: { stage: "rising", estimatedWindow: "3-7天", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-14",
  },
  {
    id: "t2",
    platform: "instagram",
    title: "Colorful Drink Layering",
    description: "色彩分层饮品展示在Instagram Reels食品饮料类目中增长最快。高饱和度、对比色分层、慢动作倒液是核心视觉元素。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 210000000, likes: 19500000, shares: 3800000, comments: 1200000, growthRate: 8, heatScore: 0 },
    format: "short_video",
    tags: ["ColorfulDrink", "drinkstagram", "foodart", "satisfying"],
    country: "KR",
    language: "ko",
    emotion: "excitement",
    demographicAffinity: { age_18_24: 0.55, age_25_34: 0.30, age_35_44: 0.10, female: 0.68, male: 0.32 },
    audienceOverlap: 85,
    lifecycle: { stage: "peak", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "high" },
    createdAt: "2026-06-10",
  },
  {
    id: "t3",
    platform: "tiktok",
    title: "Clean Girl Morning Routine",
    description: "极简主义晨间日常内容持续走热，饮品在其中扮演核心道具角色。抹茶、康普茶、精品咖啡是主要关联品类。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 180000000, likes: 15500000, shares: 2900000, comments: 950000, growthRate: 18, heatScore: 0 },
    format: "hashtag",
    tags: ["CleanGirl", "morningroutine", "matcha", "wellness"],
    country: "US",
    language: "en",
    emotion: "calm",
    demographicAffinity: { age_18_24: 0.45, age_25_34: 0.40, age_35_44: 0.12, female: 0.88, male: 0.12 },
    audienceOverlap: 78,
    lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "medium" },
    createdAt: "2026-06-13",
  },
  {
    id: "t4",
    platform: "tiktok",
    title: "Boba ASMR Compilation",
    description: "珍珠/波霸ASMR内容持续走热：煮珍珠的声音、珍珠掉入杯中慢镜头、吸管戳入塑封声。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 155000000, likes: 13500000, shares: 4100000, comments: 2100000, growthRate: 3, heatScore: 0 },
    format: "hashtag",
    tags: ["BobaASMR", "boba", "tapioca", "satisfyingsounds"],
    country: "TH",
    language: "th",
    emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.60, age_25_34: 0.25, age_35_44: 0.10, female: 0.72, male: 0.28 },
    audienceOverlap: 88,
    lifecycle: { stage: "peak", estimatedWindow: "不建议单独进入", crossPlatform: true, competitorDensity: "high" },
    createdAt: "2026-06-01",
  },
  {
    id: "t5",
    platform: "youtube",
    title: "Behind the Scenes — Tea Shop Operations",
    description: "饮品店幕后运营内容在YouTube Food频道增长迅速。观众对'一天卖多少杯'、'新品研发过程'等真实幕后内容有强烈好奇心。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 89000000, likes: 7200000, shares: 1100000, comments: 1800000, growthRate: 22, heatScore: 0 },
    format: "long_video",
    tags: ["BehindTheScenes", "smallbusiness", "bubbleteashop", "dayinlife"],
    country: "SG",
    language: "en",
    emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.30, age_25_34: 0.42, age_35_44: 0.20, female: 0.58, male: 0.42 },
    audienceOverlap: 82,
    lifecycle: { stage: "rising", estimatedWindow: "2-4周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-12",
  },
  {
    id: "t6",
    platform: "tiktok",
    title: "Emotional Support Drink",
    description: "将喝奶茶与情绪价值绑定，用幽默方式展示'今天很烂但我有奶茶'。自嘲+relatable是核心表达方式。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 125000000, likes: 11800000, shares: 3500000, comments: 2800000, growthRate: 31, heatScore: 0 },
    format: "audio",
    tags: ["EmotionalSupport", "relatable", "selfcare", "treatyourself"],
    country: "US",
    language: "en",
    emotion: "empathy",
    demographicAffinity: { age_18_24: 0.65, age_25_34: 0.28, age_35_44: 0.05, female: 0.78, male: 0.22 },
    audienceOverlap: 90,
    lifecycle: { stage: "rising", estimatedWindow: "1周", crossPlatform: true, competitorDensity: "medium" },
    riskFlags: [{ type: "cultural_sensitivity", level: "low", note: "部分内容涉及宗教符号隐喻，中东市场发布前需本地团队review" }],
    createdAt: "2026-06-15",
  },
  {
    id: "t7",
    platform: "instagram",
    title: "Minimalist Cafe Vibes",
    description: "极简咖啡厅/茶饮店美学内容在Instagram持续高热。核心是空间设计、光线、产品摆放的视觉美感。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 95000000, likes: 14200000, shares: 1800000, comments: 620000, growthRate: -3, heatScore: 0 },
    format: "short_video",
    tags: ["CafeVibes", "minimalist", "store design", "coffeeshop"],
    country: "JP",
    language: "ja",
    emotion: "calm",
    demographicAffinity: { age_18_24: 0.32, age_25_34: 0.45, age_35_44: 0.18, female: 0.75, male: 0.25 },
    audienceOverlap: 68,
    lifecycle: { stage: "peak", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "medium" },
    createdAt: "2026-05-20",
  },
  {
    id: "t8",
    platform: "tiktok",
    title: "Duet This — Drink Review",
    description: "双屏互动式饮品测评——创作者喝一口，留半边给其他创作者duet反应。TikTok食品饮料赛道新的互动范式。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 72000000, likes: 6400000, shares: 5200000, comments: 3100000, growthRate: 35, heatScore: 0 },
    format: "challenge",
    tags: ["DuetThis", "drinkreview", "react", "collab"],
    country: "US",
    language: "en",
    emotion: "humor",
    demographicAffinity: { age_18_24: 0.70, age_25_34: 0.22, age_35_44: 0.06, female: 0.62, male: 0.38 },
    audienceOverlap: 84,
    lifecycle: { stage: "rising", estimatedWindow: "3-5天", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-15",
  },
  {
    id: "t9",
    platform: "youtube_shorts",
    title: "Genshin Impact 5.0 Hype",
    description: "Genshin Impact 5.0版本即将上线，社区创作内容爆发。茶饮品牌虽与游戏无直接关联，但受众高度重合——18-28岁亚裔Gen Z是核心消费群。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 165000000, likes: 14200000, shares: 3800000, comments: 4200000, growthRate: 28, heatScore: 0 },
    format: "short_video",
    tags: ["GenshinImpact", "hoyoverse", "gaming", "anime"],
    country: "JP",
    language: "ja",
    emotion: "excitement",
    demographicAffinity: { age_18_24: 0.72, age_25_34: 0.20, age_35_44: 0.06, female: 0.48, male: 0.52 },
    audienceOverlap: 76,
    lifecycle: { stage: "rising", estimatedWindow: "2-3周", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-14",
  },
  {
    id: "t10",
    platform: "tiktok",
    title: "ASMR Unboxing Tea Collections",
    description: "茶包/茶具开箱ASMR在TikTok上快速积累流量。精致的东方风格包装盒和茶具在开箱过程中呈现极高的视觉满足感。",
    thumbnailUrl: "",
    url: "",
    metrics: { views: 68000000, likes: 5900000, shares: 1800000, comments: 880000, growthRate: 42, heatScore: 0 },
    format: "audio",
    tags: ["Unboxing", "ASMR", "tea collection", "satisfying"],
    country: "CN",
    language: "zh",
    emotion: "awe",
    demographicAffinity: { age_18_24: 0.50, age_25_34: 0.35, age_35_44: 0.12, female: 0.80, male: 0.20 },
    audienceOverlap: 86,
    lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-16",
  },
  // === Expanded: 20 more trends for filter coverage ===
  {
    id: "t11", platform: "tiktok", title: "K-Pop Idol Drink Challenge",
    description: "韩国偶像团体在直播中提及奶茶品牌引发粉丝大规模二创，TikTok上#IdolDrink挑战三天内破5亿播放。粉丝模仿偶像搭配饮品并在视频中Tag品牌。",
    thumbnailUrl: "", url: "",
    metrics: { views: 280000000, likes: 32000000, shares: 8500000, comments: 6200000, growthRate: 45, heatScore: 0 },
    format: "challenge", tags: ["IdolDrink", "Kpop", "fandom", "boba"],
    country: "KR", language: "ko", emotion: "excitement",
    demographicAffinity: { age_18_24: 0.75, age_25_34: 0.18, age_35_44: 0.05, female: 0.88, male: 0.12 },
    audienceOverlap: 80, lifecycle: { stage: "rising", estimatedWindow: "3-5天", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-15",
  },
  {
    id: "t12", platform: "instagram", title: "Sunset Gradient Latte Art",
    description: "日式渐层拿铁拉花在Instagram Reels上病毒式传播。咖啡师利用天然食材色素（蝶豆花、甜菜根、抹茶）创造日落渐层效果。",
    thumbnailUrl: "", url: "",
    metrics: { views: 145000000, likes: 18800000, shares: 3200000, comments: 980000, growthRate: 22, heatScore: 0 },
    format: "short_video", tags: ["LatteArt", "gradient", "coffeeart", "sunset"],
    country: "JP", language: "ja", emotion: "awe",
    demographicAffinity: { age_18_24: 0.40, age_25_34: 0.42, age_35_44: 0.15, female: 0.72, male: 0.28 },
    audienceOverlap: 73, lifecycle: { stage: "peak", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "medium" },
    createdAt: "2026-06-08",
  },
  {
    id: "t13", platform: "youtube_shorts", title: "What I Drink in a Day — Wellness Edition",
    description: "YouTube Shorts上'一天喝什么'系列在wellness赛道爆发。内容聚焦功能性饮品（康普茶、抹茶、草本茶），强调健康生活方式。",
    thumbnailUrl: "", url: "",
    metrics: { views: 92000000, likes: 7800000, shares: 1500000, comments: 620000, growthRate: 19, heatScore: 0 },
    format: "short_video", tags: ["WhatIDrink", "wellness", "healthylifestyle", "functional"],
    country: "US", language: "en", emotion: "calm",
    demographicAffinity: { age_18_24: 0.35, age_25_34: 0.48, age_35_44: 0.14, female: 0.85, male: 0.15 },
    audienceOverlap: 81, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-14",
  },
  {
    id: "t14", platform: "tiktok", title: "Nostalgia 90s Snack Comeback",
    description: "怀旧零食回归内容席卷TikTok食品赛道——90年代的糖果、饮料、零食包装复刻引发'童年记忆'情绪共鸣。品牌借势推出经典复刻口味。",
    thumbnailUrl: "", url: "",
    metrics: { views: 175000000, likes: 21500000, shares: 4200000, comments: 3500000, growthRate: 28, heatScore: 0 },
    format: "hashtag", tags: ["Nostalgia", "90s", "throwback", "snack"],
    country: "US", language: "en", emotion: "nostalgia",
    demographicAffinity: { age_18_24: 0.42, age_25_34: 0.40, age_35_44: 0.15, female: 0.58, male: 0.42 },
    audienceOverlap: 74, lifecycle: { stage: "rising", estimatedWindow: "2-3周", crossPlatform: true, competitorDensity: "medium" },
    createdAt: "2026-06-13",
  },
  {
    id: "t15", platform: "instagram", title: "Korean Cafe Tour Series",
    description: "韩国圣水洞/延南洞精品咖啡馆探店系列在Instagram爆火。精致空间设计+饮品特写+韩文手写菜单成为内容范式。",
    thumbnailUrl: "", url: "",
    metrics: { views: 132000000, likes: 16200000, shares: 2800000, comments: 1100000, growthRate: 15, heatScore: 0 },
    format: "short_video", tags: ["KoreanCafe", "cafetour", "Seoul", "coffeeshop"],
    country: "KR", language: "ko", emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.55, age_25_34: 0.33, age_35_44: 0.10, female: 0.80, male: 0.20 },
    audienceOverlap: 69, lifecycle: { stage: "peak", estimatedWindow: "2-4周", crossPlatform: true, competitorDensity: "high" },
    createdAt: "2026-05-28",
  },
  {
    id: "t16", platform: "tiktok", title: "Mukbang Tea Edition — 10 Cups Challenge",
    description: "泰国创作者发起10杯奶茶挑战赛，一口气试喝10个品牌的招牌饮品并评分。戏剧化的反应和排名悬念推动观看时长。",
    thumbnailUrl: "", url: "",
    metrics: { views: 210000000, likes: 24800000, shares: 5600000, comments: 4800000, growthRate: 38, heatScore: 0 },
    format: "challenge", tags: ["Mukbang", "teachallenge", "drinkreview", "10cups"],
    country: "TH", language: "th", emotion: "humor",
    demographicAffinity: { age_18_24: 0.68, age_25_34: 0.24, age_35_44: 0.06, female: 0.62, male: 0.38 },
    audienceOverlap: 71, lifecycle: { stage: "rising", estimatedWindow: "3-5天", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-16",
  },
  {
    id: "t17", platform: "youtube", title: "The Art of Chinese Tea Ceremony — Explained",
    description: "YouTube深度内容频道开始系统性地介绍中国茶道文化。长视频格式讲解工夫茶、茶器选择、冲泡技巧，吸引文化好奇心观众。",
    thumbnailUrl: "", url: "",
    metrics: { views: 48000000, likes: 5200000, shares: 980000, comments: 720000, growthRate: 25, heatScore: 0 },
    format: "long_video", tags: ["TeaCeremony", "ChineseCulture", "kungfutea", "explained"],
    country: "CN", language: "zh", emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.25, age_25_34: 0.45, age_35_44: 0.25, female: 0.55, male: 0.45 },
    audienceOverlap: 88, lifecycle: { stage: "rising", estimatedWindow: "2-4周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-12",
  },
  {
    id: "t18", platform: "tiktok", title: "Filipino Halo-Halo Summer Trend",
    description: "菲律宾国民甜品Halo-Halo在TikTok上成为全球夏日饮品趋势。碎冰、炼乳、各色配料层层堆叠的视觉冲击力让内容跨文化传播。",
    thumbnailUrl: "", url: "",
    metrics: { views: 165000000, likes: 15800000, shares: 3900000, comments: 2100000, growthRate: 32, heatScore: 0 },
    format: "short_video", tags: ["HaloHalo", "Filipino", "summerdrink", "colorful"],
    country: "PH", language: "tl", emotion: "joy",
    demographicAffinity: { age_18_24: 0.58, age_25_34: 0.28, age_35_44: 0.10, female: 0.68, male: 0.32 },
    audienceOverlap: 62, lifecycle: { stage: "peak", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "medium" },
    createdAt: "2026-06-05",
  },
  {
    id: "t19", platform: "instagram", title: "Minimalist Matcha Moments",
    description: "日式极简抹茶内容在Instagram持续走热。核心视觉元素：手工打抹茶过程、陶器茶碗质感、自然光下的绿色渐变。品牌大量合作此类内容。",
    thumbnailUrl: "", url: "",
    metrics: { views: 88000000, likes: 13200000, shares: 1700000, comments: 580000, growthRate: 10, heatScore: 0 },
    format: "short_video", tags: ["Matcha", "minimalist", "japanesetea", "ceremony"],
    country: "JP", language: "ja", emotion: "calm",
    demographicAffinity: { age_18_24: 0.32, age_25_34: 0.45, age_35_44: 0.18, female: 0.78, male: 0.22 },
    audienceOverlap: 84, lifecycle: { stage: "peak", estimatedWindow: "2-3周", crossPlatform: true, competitorDensity: "high" },
    createdAt: "2026-05-25",
  },
  {
    id: "t20", platform: "tiktok", title: "Spill the Tea — Story Time Trend",
    description: "创作者用'喝茶'场景配合戏剧化的第一人称故事讲述。'Spill the tea'双关语（既指倒茶又指爆料）让品牌自然植入故事场景。",
    thumbnailUrl: "", url: "",
    metrics: { views: 245000000, likes: 29500000, shares: 7200000, comments: 5800000, growthRate: 40, heatScore: 0 },
    format: "audio", tags: ["SpillTheTea", "storytime", "tea", "drama"],
    country: "US", language: "en", emotion: "humor",
    demographicAffinity: { age_18_24: 0.65, age_25_34: 0.28, age_35_44: 0.05, female: 0.82, male: 0.18 },
    audienceOverlap: 87, lifecycle: { stage: "rising", estimatedWindow: "1周", crossPlatform: true, competitorDensity: "low" },
    riskFlags: [{ type: "brand_safety", level: "low", note: "故事内容可能涉及敏感话题，品牌合作前需审核具体创作者内容" }],
    createdAt: "2026-06-15",
  },
  {
    id: "t21", platform: "youtube_shorts", title: "Vietnamese Egg Coffee Goes Global",
    description: "越南蛋咖啡在国际美食短视频中出圈。奶油蛋泡+浓缩咖啡的视觉层次和独特口感引发全球模仿。东南亚饮品文化的海外破圈案例。",
    thumbnailUrl: "", url: "",
    metrics: { views: 112000000, likes: 9800000, shares: 2100000, comments: 1450000, growthRate: 33, heatScore: 0 },
    format: "short_video", tags: ["EggCoffee", "Vietnamese", "unique", "coffee"],
    country: "VN", language: "vi", emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.48, age_25_34: 0.35, age_35_44: 0.14, female: 0.55, male: 0.45 },
    audienceOverlap: 58, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-14",
  },
  {
    id: "t22", platform: "tiktok", title: "French Patisserie × Tea Pairing",
    description: "法式甜点配茶内容在TikTok食品赛道增长迅速。马卡龙配乌龙、可颂配普洱——跨文化搭配激发美食KOL创作。",
    thumbnailUrl: "", url: "",
    metrics: { views: 78000000, likes: 8200000, shares: 1400000, comments: 620000, growthRate: 18, heatScore: 0 },
    format: "hashtag", tags: ["TeaPairing", "patisserie", "french", "foodpairing"],
    country: "FR", language: "fr", emotion: "joy",
    demographicAffinity: { age_18_24: 0.28, age_25_34: 0.45, age_35_44: 0.22, female: 0.75, male: 0.25 },
    audienceOverlap: 72, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-11",
  },
  {
    id: "t23", platform: "instagram", title: "Berlin Club Scene — Mate Tea Culture",
    description: "柏林电子音乐俱乐部场景中Mate茶文化成为Instagram热门话题。年轻人在派对中以Mate茶替代酒精，健康派对文化趋势。",
    thumbnailUrl: "", url: "",
    metrics: { views: 62000000, likes: 5500000, shares: 980000, comments: 480000, growthRate: 14, heatScore: 0 },
    format: "short_video", tags: ["MateTea", "Berlin", "clubculture", "sober"],
    country: "DE", language: "de", emotion: "excitement",
    demographicAffinity: { age_18_24: 0.60, age_25_34: 0.30, age_35_44: 0.08, female: 0.48, male: 0.52 },
    audienceOverlap: 51, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-09",
  },
  {
    id: "t24", platform: "tiktok", title: "Bubble Tea ASMR — Satisfying Tapioca Sounds",
    description: "珍珠吸管声、椰果挤压声、冰块碰撞声组成的奶茶ASMR内容在TikTok上持续走热。声音设计比画面更重要。",
    thumbnailUrl: "", url: "",
    metrics: { views: 195000000, likes: 17500000, shares: 4800000, comments: 2200000, growthRate: 8, heatScore: 0 },
    format: "audio", tags: ["BubbleTeaASMR", "tapioca", "satisfying", "sound"],
    country: "SG", language: "en", emotion: "calm",
    demographicAffinity: { age_18_24: 0.62, age_25_34: 0.28, age_35_44: 0.08, female: 0.75, male: 0.25 },
    audienceOverlap: 82, lifecycle: { stage: "peak", estimatedWindow: "不建议单独进入", crossPlatform: true, competitorDensity: "high" },
    createdAt: "2026-05-20",
  },
  {
    id: "t25", platform: "youtube", title: "Tea Farm Documentary — From Leaf to Cup",
    description: "YouTube纪录片风格的茶庄园探访内容增长明显。观众对茶的生产过程、种植环境和工艺细节有深层好奇心。长视频格式的完播率高于平台均值。",
    thumbnailUrl: "", url: "",
    metrics: { views: 35000000, likes: 4200000, shares: 620000, comments: 520000, growthRate: 12, heatScore: 0 },
    format: "long_video", tags: ["TeaFarm", "documentary", "howitsmade", "tea"],
    country: "MY", language: "ms", emotion: "curiosity",
    demographicAffinity: { age_18_24: 0.20, age_25_34: 0.40, age_35_44: 0.32, female: 0.52, male: 0.48 },
    audienceOverlap: 76, lifecycle: { stage: "rising", estimatedWindow: "3-4周", crossPlatform: false, competitorDensity: "low" },
    createdAt: "2026-06-10",
  },
  {
    id: "t26", platform: "tiktok", title: "Indonesian Es Teh — Sweet Tea Revolution",
    description: "印尼甜茶(Es Teh)在TikTok上掀起本地饮品全球化浪潮。大容量袋装+夸张甜度+街头文化包装让内容瞬间识别。体现了'本地饮品如何走向全球'的内容范式。",
    thumbnailUrl: "", url: "",
    metrics: { views: 145000000, likes: 12500000, shares: 3100000, comments: 2800000, growthRate: 27, heatScore: 0 },
    format: "short_video", tags: ["EsTeh", "Indonesian", "sweettea", "streetfood"],
    country: "ID", language: "id", emotion: "joy",
    demographicAffinity: { age_18_24: 0.62, age_25_34: 0.28, age_35_44: 0.08, female: 0.55, male: 0.45 },
    audienceOverlap: 55, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "low" },
    createdAt: "2026-06-14",
  },
  {
    id: "t27", platform: "instagram", title: "Cottagecore Tea Party Aesthetic",
    description: "田园风茶会美学内容在Instagram持续走热。野花、手工陶器、蕾丝桌布、自制果酱——'cottagecore'审美与茶文化的天然交汇。",
    thumbnailUrl: "", url: "",
    metrics: { views: 78000000, likes: 11200000, shares: 1500000, comments: 420000, growthRate: -5, heatScore: 0 },
    format: "short_video", tags: ["Cottagecore", "teaparty", "aesthetic", "vintage"],
    country: "UK", language: "en", emotion: "nostalgia",
    demographicAffinity: { age_18_24: 0.52, age_25_34: 0.35, age_35_44: 0.10, female: 0.92, male: 0.08 },
    audienceOverlap: 75, lifecycle: { stage: "peak", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "medium" },
    createdAt: "2026-05-30",
  },
  {
    id: "t28", platform: "tiktok", title: "Dance Challenge with a Drink",
    description: "新的TikTok舞蹈挑战以手持饮品为固定道具——品牌饮品自然出现在每个参赛视频中。品牌蓝V账号发起后UGC内容指数级增长。",
    thumbnailUrl: "", url: "",
    metrics: { views: 320000000, likes: 38000000, shares: 9200000, comments: 4500000, growthRate: 55, heatScore: 0 },
    format: "challenge", tags: ["DrinkDance", "dancechallenge", "viral", "trending"],
    country: "US", language: "en", emotion: "excitement",
    demographicAffinity: { age_18_24: 0.78, age_25_34: 0.18, age_35_44: 0.03, female: 0.70, male: 0.30 },
    audienceOverlap: 85, lifecycle: { stage: "rising", estimatedWindow: "3-5天", crossPlatform: true, competitorDensity: "low" },
    riskFlags: [{ type: "cultural_sensitivity", level: "low", note: "部分舞蹈动作可能涉及文化挪用争议，品牌发起前需本地团队审核" }],
    createdAt: "2026-06-16",
  },
  {
    id: "t29", platform: "youtube_shorts", title: "Toronto Bubble Tea Crawl",
    description: "多伦多奶茶一条街探店内容在YouTube Shorts走红。加拿大作为北美奶茶文化重镇，内容聚焦多元文化融合的饮品创新。",
    thumbnailUrl: "", url: "",
    metrics: { views: 55000000, likes: 4800000, shares: 880000, comments: 520000, growthRate: 20, heatScore: 0 },
    format: "short_video", tags: ["BubbleTea", "Toronto", "foodcrawl", "canada"],
    country: "CA", language: "en", emotion: "joy",
    demographicAffinity: { age_18_24: 0.55, age_25_34: 0.32, age_35_44: 0.10, female: 0.72, male: 0.28 },
    audienceOverlap: 68, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: false, competitorDensity: "medium" },
    createdAt: "2026-06-13",
  },
  {
    id: "t30", platform: "tiktok", title: "Cozy Rainy Day Tea Routine",
    description: "雨天宅家喝茶的cozy内容在TikTok持续走热。窗边雨声、热茶蒸汽、一本书的慢生活美学——品牌可以极低成本复刻。",
    thumbnailUrl: "", url: "",
    metrics: { views: 118000000, likes: 14200000, shares: 2200000, comments: 850000, growthRate: 24, heatScore: 0 },
    format: "audio", tags: ["CozyVibes", "rainyday", "tea", "slowliving"],
    country: "UK", language: "en", emotion: "calm",
    demographicAffinity: { age_18_24: 0.42, age_25_34: 0.40, age_35_44: 0.15, female: 0.85, male: 0.15 },
    audienceOverlap: 79, lifecycle: { stage: "rising", estimatedWindow: "1-2周", crossPlatform: true, competitorDensity: "medium" },
    createdAt: "2026-06-14",
  },
];

export const kols: KOL[] = [
  {
    id: "k1",
    handle: "@bobabae_",
    platform: "tiktok",
    displayName: "Boba Bae",
    avatarUrl: "",
    followers: 120000,
    avgEngagementRate: 4.8,
    contentStyleTags: ["ASMR", "aesthetic"],
    audienceProfile: { age: "18-28", gender: "82% Female", interests: ["boba", "korean food", "aesthetic"], region: "US" },
    recentViralPosts: [
      { postTitle: "Taro ASMR", views: 520000, engagement: 48000, platform: "tiktok" },
      { postTitle: "Matcha foam pour", views: 380000, engagement: 32000, platform: "tiktok" },
      { postTitle: "Brown sugar boba slow-mo", views: 720000, engagement: 65000, platform: "tiktok" },
      { postTitle: "Strawberry matcha latte", views: 290000, engagement: 25000, platform: "instagram" },
      { postTitle: "Tea shop sunrise ASMR", views: 440000, engagement: 38000, platform: "tiktok" },
      { postTitle: "Coconut jelly compilation", views: 610000, engagement: 52000, platform: "tiktok" },
    ],
    brandCollabHistory: [{ brand: "Mixue", date: "2025-03", type: "产品测评" }, { brand: "Local boba shop", date: "2025-06", type: "探店" }],
    estimatedCostRange: { min: 800, max: 1500 },
    brandFitScore: 9.2,
    audienceOverlap: 78,
  },
  {
    id: "k2",
    handle: "@teawithjade",
    platform: "instagram",
    displayName: "Jade's Tea Diary",
    avatarUrl: "",
    followers: 340000,
    avgEngagementRate: 3.2,
    contentStyleTags: ["lifestyle", "food_review"],
    audienceProfile: { age: "22-35", gender: "75% Female", interests: ["tea", "wellness", "travel", "food photography"], region: "US/UK" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Heytea", date: "2025-11", type: "品牌大使" }],
    estimatedCostRange: { min: 1500, max: 3000 },
    brandFitScore: 8.7,
    audienceOverlap: 72,
  },
  {
    id: "k3",
    handle: "@drinkmuse",
    platform: "tiktok",
    displayName: "Drink Muse",
    avatarUrl: "",
    followers: 89000,
    avgEngagementRate: 6.1,
    contentStyleTags: ["educational", "comedic"],
    audienceProfile: { age: "20-30", gender: "60% Female", interests: ["food science", "drinks", "comedy"], region: "US" },
    recentViralPosts: [],
    brandCollabHistory: [],
    estimatedCostRange: { min: 500, max: 1000 },
    brandFitScore: 8.5,
    audienceOverlap: 65,
  },
  {
    id: "k4",
    handle: "@aesthetic.eats",
    platform: "instagram",
    displayName: "Aesthetic Eats",
    avatarUrl: "",
    followers: 520000,
    avgEngagementRate: 2.5,
    contentStyleTags: ["aesthetic", "lifestyle"],
    audienceProfile: { age: "18-30", gender: "88% Female", interests: ["food styling", "minimalism", "cafe culture"], region: "US/Global" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Starbucks", date: "2025-08", type: "季节性campaign" }, { brand: "Blue Bottle", date: "2025-12", type: "探店" }],
    estimatedCostRange: { min: 3000, max: 6000 },
    brandFitScore: 7.8,
    audienceOverlap: 58,
  },
  {
    id: "k5",
    handle: "@streetfoodhunter",
    platform: "youtube",
    displayName: "Street Food Hunter",
    avatarUrl: "",
    followers: 280000,
    avgEngagementRate: 4.2,
    contentStyleTags: ["food_review", "lifestyle"],
    audienceProfile: { age: "22-40", gender: "55% Male", interests: ["street food", "travel", "culture"], region: "US/Global" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Din Tai Fung", date: "2026-01", type: "纪录片式合作" }],
    estimatedCostRange: { min: 2000, max: 4500 },
    brandFitScore: 7.5,
    audienceOverlap: 48,
  },
  {
    id: "k6",
    handle: "@matchamandy",
    platform: "tiktok",
    displayName: "Matcha Mandy",
    avatarUrl: "",
    followers: 65000,
    avgEngagementRate: 7.3,
    contentStyleTags: ["ASMR", "educational"],
    audienceProfile: { age: "20-28", gender: "80% Female", interests: ["matcha", "tea culture", "wellness"], region: "US" },
    recentViralPosts: [],
    brandCollabHistory: [],
    estimatedCostRange: { min: 400, max: 800 },
    brandFitScore: 8.9,
    audienceOverlap: 82,
  },
  {
    id: "k7",
    handle: "@seoulsipper",
    platform: "tiktok",
    displayName: "Seoul Sipper",
    avatarUrl: "",
    followers: 185000,
    avgEngagementRate: 5.2,
    contentStyleTags: ["aesthetic", "lifestyle"],
    audienceProfile: { age: "18-28", gender: "78% Female", interests: ["Korean culture", "cafe", "matcha", "minimalism"], region: "KR/Global" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Osulloc", date: "2026-02", type: "品牌大使" }],
    estimatedCostRange: { min: 800, max: 1800 },
    brandFitScore: 8.3,
    audienceOverlap: 68,
  },
  {
    id: "k8",
    handle: "@teatalkjp",
    platform: "youtube",
    displayName: "Tea Talk Japan",
    avatarUrl: "",
    followers: 150000,
    avgEngagementRate: 3.8,
    contentStyleTags: ["educational", "lifestyle"],
    audienceProfile: { age: "25-45", gender: "55% Female", interests: ["Japanese tea", "tea ceremony", "culture", "travel"], region: "JP/Global" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Ippodo Tea", date: "2025-09", type: "纪录片合作" }],
    estimatedCostRange: { min: 1500, max: 3500 },
    brandFitScore: 7.8,
    audienceOverlap: 65,
  },
  {
    id: "k9",
    handle: "@bangkokbrew",
    platform: "instagram",
    displayName: "Bangkok Brew",
    avatarUrl: "",
    followers: 95000,
    avgEngagementRate: 5.8,
    contentStyleTags: ["food_review", "aesthetic"],
    audienceProfile: { age: "20-32", gender: "70% Female", interests: ["Thai tea", "street food", "cafe", "travel"], region: "TH/SEA" },
    recentViralPosts: [],
    brandCollabHistory: [],
    estimatedCostRange: { min: 500, max: 1200 },
    brandFitScore: 7.5,
    audienceOverlap: 52,
  },
  {
    id: "k10",
    handle: "@paristeatime",
    platform: "instagram",
    displayName: "Paris Tea Time",
    avatarUrl: "",
    followers: 220000,
    avgEngagementRate: 3.5,
    contentStyleTags: ["aesthetic", "lifestyle"],
    audienceProfile: { age: "25-40", gender: "82% Female", interests: ["French patisserie", "afternoon tea", "wellness", "fashion"], region: "FR/Europe" },
    recentViralPosts: [],
    brandCollabHistory: [{ brand: "Mariage Frères", date: "2025-11", type: "联名campaign" }],
    estimatedCostRange: { min: 1200, max: 2800 },
    brandFitScore: 7.2,
    audienceOverlap: 56,
  },
];

export const ips: IP[] = [
  {
    id: "ip1",
    name: "Jujutsu Kaisen",
    category: "anime",
    heatScore: 91,
    trendDirection: "up",
    audienceOverlap: 72,
    audienceProfile: "18-28岁，男女均衡，偏亚裔+Gen Z，重度社交媒体使用",
    collabPrecedents: [{ brand: "McDonald's", year: 2024, description: "联名包装+限定酱料", socialImpression: "2亿+", url: "https://en.wikipedia.org/wiki/Jujutsu_Kaisen" }],
    feasibility: "high",
    competitorOccupied: false,
    imageUrl: "",
  },
  {
    id: "ip2",
    name: "Inside Out 3",
    category: "movie",
    heatScore: 85,
    trendDirection: "up",
    audienceOverlap: 65,
    audienceProfile: "全年龄段，偏女性+家庭观众，跨代际传播能力强",
    collabPrecedents: [],
    feasibility: "high",
    competitorOccupied: false,
    imageUrl: "",
  },
  {
    id: "ip3",
    name: "Hello Kitty",
    category: "character",
    heatScore: 78,
    trendDirection: "stable",
    audienceOverlap: 72,
    audienceProfile: "18-35岁女性，全球认知度极高，Y2K复古风加持",
    collabPrecedents: [{ brand: "Mixue", year: 2025, description: "联名杯+周边", socialImpression: "5000万+", url: "https://en.wikipedia.org/wiki/Hello_Kitty" }, { brand: "多个茶饮品牌", description: "联名杯+周边", socialImpression: "5000万+" },
      { brand: "多个茶饮品牌", year: 2024, description: "食品联名", socialImpression: "N/A" },
    ],
    feasibility: "medium",
    competitorOccupied: true,
    imageUrl: "",
  },
  {
    id: "ip4",
    name: "Minecraft Movie",
    category: "movie",
    heatScore: 82,
    trendDirection: "up",
    audienceOverlap: 55,
    audienceProfile: "12-28岁男性为主，游戏玩家群体，Z世代+Alpha世代",
    collabPrecedents: [{ brand: "Burger King", year: 2025, description: "限定套餐+游戏内道具", socialImpression: "1.5亿+", url: "https://en.wikipedia.org/wiki/Minecraft" }],
    feasibility: "high",
    competitorOccupied: false,
    imageUrl: "",
  },
  {
    id: "ip5",
    name: "Stardew Valley",
    category: "game",
    heatScore: 72,
    trendDirection: "up",
    audienceOverlap: 60,
    audienceProfile: "20-35岁，男女均衡，cozy gamer群体，与茶饮'治愈'属性高度契合",
    collabPrecedents: [],
    feasibility: "high",
    competitorOccupied: false,
    imageUrl: "",
  },
  {
    id: "ip6",
    name: "Sad Hamster Meme",
    category: "meme",
    heatScore: 68,
    trendDirection: "down",
    audienceOverlap: 42,
    audienceProfile: "16-25岁，Gen Z为主，meme文化重度消费者",
    collabPrecedents: [],
    feasibility: "low",
    competitorOccupied: false,
    imageUrl: "",
  },
  {
    id: "ip7",
    name: "Genshin Impact",
    category: "game",
    heatScore: 88,
    trendDirection: "up",
    audienceOverlap: 76,
    audienceProfile: "18-28岁，男女均衡，亚裔Gen Z为主，二次元+游戏圈层，重度社交媒体使用",
    collabPrecedents: [{ brand: "KFC China", year: 2023, description: "联名套餐+限定周边+cosplay活动", socialImpression: "5亿+", url: "https://en.wikipedia.org/wiki/Genshin_Impact" }, { brand: "Heytea", year: 2023, description: "联名套餐+限定周边+cosplay活动", socialImpression: "5亿+" },
      { brand: "Heytea", year: 2024, description: "角色主题杯身限定", socialImpression: "1.2亿+" },
    ],
    feasibility: "medium",
    competitorOccupied: true,
    imageUrl: "",
  },
  {
    id: "ip8",
    name: "Animal Crossing",
    category: "game",
    heatScore: 65,
    trendDirection: "stable",
    audienceOverlap: 58,
    audienceProfile: "20-35岁，女性为主，cozy gamer群体，注重生活美学和治愈体验",
    collabPrecedents: [],
    feasibility: "high",
    competitorOccupied: false,
    imageUrl: "",
  },
];

export const calendarEvents: CalendarEvent[] = [
  { id: "cal1", date: "2026-02-09", region: "US", country: "US", name: "Super Bowl", type: "sports", suggestion: "赛事观赛场景 → 限定套餐 + 观赛主题杯身" },
  { id: "cal2", date: "2026-04-17", region: "US", country: "US", name: "Coachella", type: "festival", suggestion: "音乐节场景 → 联名特调 + 社交媒体打卡活动" },
  { id: "cal3", date: "2026-07-04", region: "US", country: "US", name: "Independence Day", type: "holiday", suggestion: "国庆主题 → 红蓝白限定杯身 + 爱国主题UGC" },
  { id: "cal4", date: "2026-10-31", region: "US", country: "US", name: "Halloween", type: "cultural", suggestion: "南瓜/幽灵主题 → 限定口味 + 门店装饰 + AR滤镜" },
  { id: "cal5", date: "2026-11-26", region: "US", country: "US", name: "Thanksgiving", type: "holiday", suggestion: "感恩季 → 'Thankful for Tea' 话题 + 家庭套餐" },
  { id: "cal6", date: "2026-12-25", region: "US", country: "US", name: "Christmas", type: "holiday", suggestion: "圣诞限定 → 姜饼/薄荷口味 + 礼品卡推广" },
  { id: "cal7", date: "2026-12-26", region: "UK", country: "UK", name: "Boxing Day", type: "holiday", suggestion: "节后促销 → 限定礼盒 + 冬日暖饮系列" },
  { id: "cal8", date: "2026-07-01", region: "UK", country: "UK", name: "Wimbledon", type: "sports", suggestion: "网球赛季 → 英式下午茶主题 + 草地观赛联名" },
  { id: "cal9", date: "2026-08-30", region: "UK", country: "UK", name: "Notting Hill Carnival", type: "festival", suggestion: "加勒比文化节 → 热带水果限定 + 街头文化联名" },
  { id: "cal10", date: "2026-04-13", region: "SEA", country: "TH", name: "泼水节 (Songkran)", type: "cultural", suggestion: "泰国新年 → 清凉茶饮系列 + 泼水主题社交媒体互动" },
  { id: "cal11", date: "2026-02-17", region: "SEA", country: "SG", name: "农历新年", type: "cultural", suggestion: "春节限定 → 生肖主题杯身 + 红包营销 + 新年礼盒" },
  { id: "cal12", date: "2026-03-05", region: "SEA", country: "ID", name: "斋月 (Ramadan)", type: "cultural", suggestion: "斋月特供 → 日落开斋时段限定 + 清真认证标注 + 社区捐赠" },
  { id: "cal13", date: "2026-11-01", region: "SEA", country: "MY", name: "排灯节 (Deepavali)", type: "cultural", suggestion: "印度新年 → 金色主题限定 + 香料奶茶系列 + 节日礼品装" },
  { id: "cal14", date: "2026-01-26", region: "AU", country: "AU", name: "Australia Day", type: "holiday", suggestion: "澳洲国庆 → 南半球夏日特调 + 海滩主题pop-up" },
  { id: "cal15", date: "2026-05-22", region: "AU", country: "AU", name: "Vivid Sydney", type: "festival", suggestion: "灯光艺术节 → 发光杯身 + 灯光装置联名打卡" },
  // Missing countries
  { id: "cal16", date: "2026-07-01", region: "US", country: "CA", name: "Canada Day", type: "holiday", suggestion: "加拿大国庆 → 枫叶主题杯身 + 红白限定特调" },
  { id: "cal17", date: "2026-07-14", region: "UK", country: "FR", name: "Bastille Day", type: "holiday", suggestion: "法国国庆 → 法式甜点联名 + 蓝白红限定杯身" },
  { id: "cal18", date: "2026-10-03", region: "UK", country: "DE", name: "Oktoberfest", type: "festival", suggestion: "慕尼黑啤酒节 → 德国啤酒风味特调 + 巴伐利亚主题装饰" },
  { id: "cal19", date: "2026-06-12", region: "SEA", country: "PH", name: "Independence Day (PH)", type: "holiday", suggestion: "菲律宾独立日 → 热带水果限定 + 民族色彩杯身设计" },
  { id: "cal20", date: "2026-02-14", region: "SEA", country: "VN", name: "Tet (越南新年)", type: "cultural", suggestion: "越南春节 → 花卉主题杯身 + 年货礼盒 + 红包营销" },
  { id: "cal21", date: "2026-03-20", region: "SEA", country: "JP", name: "樱花季 (Sakura Season)", type: "cultural", suggestion: "樱花季限定 → 樱花风味特调 + 粉色系杯身 + 赏樱打卡活动" },
  { id: "cal22", date: "2026-09-15", region: "SEA", country: "KR", name: "秋夕 (Chuseok)", type: "cultural", suggestion: "韩国中秋 → 传统茶礼套装 + 韩服主题门店装饰" },
  { id: "cal23", date: "2026-10-01", region: "SEA", country: "CN", name: "中国国庆节", type: "holiday", suggestion: "黄金周限定 → 国庆主题杯身 + 旅行套餐联名" },
];

export const weeklyBrief: WeeklyBrief = {
  weekStart: "2026-06-16",
  brandName: "CHAGEE",
  topOpportunities: [
    { rank: 1, title: "Soft Life Aesthetic", audienceOverlap: 92, window: "3-7天", action: "茶道ASMR内容 + 东方美学视觉，用Soft Life audio做品牌内容", expectedBoost: "高于品牌均值40%" },
    { rank: 2, title: "Emotional Support Drink", audienceOverlap: 90, window: "1周", action: "'Find Your Calm' UGC话题发起，关联CHAGEE东方茶道的宁静感", expectedBoost: "高于品牌均值35%" },
    { rank: 3, title: "Genshin Impact 5.0 Hype", audienceOverlap: 76, window: "2-3周", action: "IP联动评估：角色主题限定杯 — 需提前联系版权方", expectedBoost: "IP联动级别提升" },
  ],
  kolRecommendations: [
    { handle: "@matchamandy", reason: "茶道垂类创作者，互动率7.3%, 粉丝精准，性价比极高", fitScore: 8.9, costRange: "$400-800/条" },
    { handle: "@bobabae_", reason: "ASMR风格与品牌调性互补, 受众重合78%, 内容社交化能力强", fitScore: 9.2, costRange: "$800-1,500/条" },
    { handle: "@teawithjade", reason: "头部食品KOL, 撬动竞品合作过的KOL是品牌信号", fitScore: 8.7, costRange: "$1,500-3,000/条" },
  ],
  ipWatchlist: [
    { name: "Jujutsu Kaisen", reason: "热度最高, 视觉性强, 尚无茶饮品牌联动", urgency: "建议1周内接触版权方" },
    { name: "Inside Out 3", reason: "电影上映窗口期, 情绪主题与饮品天然契合", urgency: "电影上映前2周启动" },
  ],
  contentCalendar: [
    { day: "Mon", content: "Soft Life ASMR × 产品制作过程展示" },
    { day: "Wed", content: "'Find Your Calm' × 产品仪式感展示" },
    { day: "Fri", content: "@matchamandy 合作内容发布 — 茶道文化深度内容" },
  ],
};
