import type { TrendTopic } from "@/types";

export const trendTopics: TrendTopic[] = [
  // ═══ 原料/口味趋势 ═══
  {
    id: "ing-1",
    category: "ingredient",
    subCategory: "coffee_tea",
    title: "云南咖啡正在成为茶饮赛道下一个核心风味",
    description: "三个头部品牌同时在推云南咖啡相关产品，从原料产地溯源到产品卖点都在强调\"云南\"标签。上游普洱产区预计2026产季增产30%，预示该赛道将在6-12个月内从早期信号进入主流竞争。",
    discussionVolume: 2400000,
    growthRate: 32,
    platforms: { tiktok: 55, instagram: 30, facebook: 15 },
    associatedBrands: ["喜茶 HEYTEA", "蜜雪冰城 MIXUE", "瑞幸 Luckin"],
    competitorDensity: "high",
    weeklyVolumes: [420000, 510000, 580000, 890000],
    evidence: [
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-06-11", content: "世界杯联名系列首次推出「云南小粒咖啡」特调，强调产地溯源" },
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-06-08", content: "「云南寻豆之旅」幕后花絮视频，展示普洱咖啡庄园" },
      { brand: "瑞幸 Luckin", platform: "tiktok", date: "2026-06-13", content: "生椰拿铁3.0升级版强调「云南高山阿拉比卡豆」作为核心卖点" },
    ],
    actionSuggestion: "三个品牌同步推出云南咖啡产品，普洱产区2026产季预计增产30%",
  },
  {
    id: "ing-2",
    category: "ingredient",
    subCategory: "fruit",
    title: "椰子口味从东南亚蔓延至全球市场",
    description: "椰椰/椰乳/生椰系列新品在三个平台合计讨论量持续攀升，且从东南亚市场向北美和欧洲溢出。椰子已成为茶饮行业仅次于芒果的第二大热带水果风味。",
    discussionVolume: 3100000,
    growthRate: 28,
    platforms: { tiktok: 62, instagram: 25, facebook: 13 },
    associatedBrands: ["蜜雪冰城 MIXUE", "瑞幸 Luckin", "CHAGEE 霸王茶姬"],
    competitorDensity: "high",
    weeklyVolumes: [580000, 650000, 820000, 1050000],
    evidence: [
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-05-25", content: "椰椰系列新品上市，强调\"东南亚椰子直采\"供应链故事" },
      { brand: "瑞幸 Luckin", platform: "tiktok", date: "2026-06-13", content: "生椰拿铁3.0版本强调\"印尼老树椰子\"产地标签" },
      { brand: "CHAGEE 霸王茶姬", platform: "instagram", date: "2026-04-28", content: "热带水果系列中椰子单品获得最高互动率" },
    ],
    actionSuggestion: "椰子供应链当前集中在印尼和菲律宾，海南及越南产区具备替代供应潜力",
  },
  {
    id: "ing-3",
    category: "ingredient",
    subCategory: "dairy",
    title: "芝士/奶盖品类在北美进入主流认知",
    description: "芝士奶盖相关话题在TikTok和Instagram的英文内容中快速增长，不再仅限中文圈。美国本土美食KOL开始自发测评\"cheese foam tea\"，品类教育正在完成。",
    discussionVolume: 1800000,
    growthRate: 22,
    platforms: { tiktok: 48, instagram: 42, facebook: 10 },
    associatedBrands: ["喜茶 HEYTEA", "CHAGEE 霸王茶姬"],
    competitorDensity: "medium",
    weeklyVolumes: [310000, 370000, 480000, 640000],
    evidence: [
      { platform: "tiktok", date: "2026-06-14", content: "美食KOL @nycfoodgirl 芝士奶盖测评视频获2.1M播放，评论区大量\"在哪里买\"提问" },
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-02-24", content: "芝士奶茶系列强调奶盖分层视觉效果，在INS Reels获高互动" },
    ],
    actionSuggestion: "美国本土KOL开始自发测评芝士奶盖产品，品类认知正在从华人圈向主流扩散",
  },

  // ═══ 品类赛道趋势 ═══
  {
    id: "cat-1",
    category: "category",
    subCategory: "tea_drink",
    title: "新茶饮海外扩张进入加速期，东南亚是主战场",
    description: "2026年上半年头部茶饮品牌在东南亚市场的开店和品牌内容密度显著增加。越南、印尼、菲律宾三国是扩张热点。品牌内容从\"华人社区\"向\"本地年轻消费者\"渗透。",
    discussionVolume: 5200000,
    growthRate: 45,
    platforms: { tiktok: 70, instagram: 20, facebook: 10 },
    associatedBrands: ["蜜雪冰城 MIXUE", "瑞幸 Luckin", "CHAGEE 霸王茶姬", "喜茶 HEYTEA"],
    competitorDensity: "high",
    weeklyVolumes: [950000, 1100000, 1300000, 1850000],
    evidence: [
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-06-14", content: "胡志明市首店开业探店视频爆发，越南TikTok美食榜前10" },
      { brand: "瑞幸 Luckin", platform: "tiktok", date: "2026-05-05", content: "新加坡第20店开业，强调东南亚市场\"本地化供应链\"策略" },
      { brand: "CHAGEE 霸王茶姬", platform: "tiktok", date: "2026-04-05", content: "马尼拉市场文化节日联名，本地化内容策略初见成效" },
    ],
    actionSuggestion: "头部品牌集中在越南、印尼、菲律宾三国开店，柬埔寨和缅甸目前为空白市场",
  },
  {
    id: "cat-2",
    category: "category",
    subCategory: "functional",
    title: "功能性饮品在北美社媒讨论量季度环比增40%",
    description: "添加胶原蛋白、益生菌、适应原（adaptogen）的饮品在TikTok和IG上形成独立内容品类。与传统茶饮的重叠度不高，但消费人群高度重合（25-35岁女性）。",
    discussionVolume: 1500000,
    growthRate: 40,
    platforms: { tiktok: 65, instagram: 30, facebook: 5 },
    associatedBrands: [],
    competitorDensity: "low",
    weeklyVolumes: [220000, 290000, 420000, 570000],
    evidence: [
      { platform: "tiktok", date: "2026-06-10", content: "\"Functional Drink Review\"话题标签下累计5.2亿播放，创作者以美国营养师和wellness KOL为主" },
      { platform: "instagram", date: "2026-06-12", content: "DTC功能性饮品品牌（Recess、Kin Euphorics）在IG保持高频内容产出" },
    ],
    actionSuggestion: "功能性饮品消费人群与茶饮高度重叠（25-35岁女性），但当前无传统茶饮品牌入局此赛道",
  },
  {
    id: "cat-3",
    category: "category",
    subCategory: "tea_drink",
    title: "茶饮\"咖啡化\"趋势：产品迭代速度成为核心竞争维度",
    description: "头部品牌月均推新频次从2025年的2-3款提升至2026年的3-5款。高频推新配合社媒预热/悬念/测评内容矩阵已成为标准打法。产品生命周期缩短，旺季一个爆品的窗口期约为2-3周。",
    discussionVolume: 2800000,
    growthRate: 18,
    platforms: { tiktok: 50, instagram: 35, facebook: 15 },
    associatedBrands: ["喜茶 HEYTEA", "瑞幸 Luckin", "蜜雪冰城 MIXUE"],
    competitorDensity: "high",
    weeklyVolumes: [550000, 620000, 740000, 890000],
    evidence: [
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-01-21", content: "芒果新品→椰子咖啡→草莓系列→夏季水果，6个月内连续4次新品发布" },
      { brand: "瑞幸 Luckin", platform: "tiktok", date: "2026-05-28", content: "9.9元咖啡节+联名+新品三重叠加，快速轮换产品线" },
    ],
    actionSuggestion: "头部品牌月均推新3-5款，产品生命周期约2-3周——这一节奏中小品牌难以复制",
  },

  // ═══ 区域市场趋势 ═══
  {
    id: "reg-1",
    category: "regional",
    subCategory: "sea",
    title: "越南市场成为茶饮品牌新焦点",
    description: "多个品牌在越南的社媒内容密度在近3个月内显著增加。蜜雪冰城胡志明市首店开业、喜茶和CHAGEE的越南话题标签讨论量也在增长。越南TikTok用户对茶饮内容的互动率远高于其他东南亚国家。",
    discussionVolume: 1200000,
    growthRate: 55,
    platforms: { tiktok: 75, instagram: 15, facebook: 10 },
    associatedBrands: ["蜜雪冰城 MIXUE"],
    competitorDensity: "medium",
    weeklyVolumes: [150000, 220000, 340000, 490000],
    evidence: [
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-06-14", content: "胡志明市首店探店内容在越南TikTok霸榜，本地消费者自发拍摄UGC内容爆发" },
      { platform: "instagram", date: "2026-06-10", content: "蜜雪东南亚负责人在IG连续两周定位胡志明市，分享本地食材市场考察照片" },
      { platform: "tiktok", date: "2026-06-01", content: "越南TikTok美食类话题#tràsữa（奶茶）标签累计播放量超50亿次" },
    ],
    actionSuggestion: "越南奶茶话题#tràsữa累计播放量超50亿次，但当前仅蜜雪冰城一个品牌开设门店",
  },
  {
    id: "reg-2",
    category: "regional",
    subCategory: "north_america",
    title: "纽约Soho商圈将成茶饮品牌北美竞争制高点",
    description: "至少两个品牌同步在纽约Soho区布局，商业地产招商信息确认了品牌签约。Soho作为北美潮流策源地，对品牌的北美市场公信力有标杆意义。",
    discussionVolume: 850000,
    growthRate: 35,
    platforms: { tiktok: 40, instagram: 50, facebook: 10 },
    associatedBrands: ["喜茶 HEYTEA", "CHAGEE 霸王茶姬"],
    competitorDensity: "high",
    weeklyVolumes: [140000, 180000, 240000, 290000],
    evidence: [
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-06-05", content: "纽约门店预热活动连续发布，定位标签显示Soho区，门店围挡揭幕内容" },
      { platform: "facebook", date: "2026-06-02", content: "Brookfield Properties招商信息暗示\"Soho旗舰铺位已签约亚洲高端茶饮品牌\"" },
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-05-20", content: "纽约首店开业内容约20条帖，覆盖门店环境/开业盛况/顾客打卡/幕后花絮" },
    ],
    actionSuggestion: "喜茶和CHAGEE同时在Soho布局，商业地产信息确认至少一个品牌已签约铺位",
  },

  // ═══ 竞品策略趋势 ═══
  {
    id: "str-1",
    category: "strategy",
    subCategory: "content",
    title: "CHAGEE与喜茶在海外市场的内容策略出现明显分化",
    description: "CHAGEE转向品牌文化深度叙事（创始人故事/茶山溯源/东方美学纪录片风格），喜茶保持高频产品推新+短平快联名节奏。两种路径代表了对\"中国茶饮出海\"的不同理解——品牌溢价 vs 产品效率。",
    discussionVolume: 950000,
    growthRate: 15,
    platforms: { tiktok: 50, instagram: 40, facebook: 10 },
    associatedBrands: ["CHAGEE 霸王茶姬", "喜茶 HEYTEA"],
    competitorDensity: "low",
    weeklyVolumes: [190000, 220000, 260000, 280000],
    evidence: [
      { brand: "CHAGEE 霸王茶姬", platform: "tiktok", date: "2026-06-15", content: "品牌历史故事系列「从云南茶山到全球化的心路」纪录片风格内容" },
      { brand: "CHAGEE 霸王茶姬", platform: "tiktok", date: "2026-06-08", content: "创始人故事，强调「东方美学」品牌叙事" },
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-06-11", content: "世界杯联名系列，撞色限定杯身，短平快产品推新节奏" },
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-04-15", content: "夏季水果系列新品上线，维持高频率推新（月均3-4款）的节奏" },
    ],
    actionSuggestion: "CHAGEE侧重品牌历史纪录片+创始人故事，喜茶侧重高频产品推新+联名，两种出海策略路径正在分化",
  },
  {
    id: "str-2",
    category: "strategy",
    subCategory: "expansion",
    title: "蜜雪冰城在东南亚采用\"低价+供应链前置\"策略",
    description: "不同于其他品牌的轻资产出海模式，蜜雪在越南同时发布了门店运营、供应链、冷链三个方向的招聘信息。其TikTok内容策略也明显侧重\"本地化供应链故事\"而非品牌调性。",
    discussionVolume: 720000,
    growthRate: 25,
    platforms: { tiktok: 60, instagram: 20, facebook: 20 },
    associatedBrands: ["蜜雪冰城 MIXUE"],
    competitorDensity: "low",
    weeklyVolumes: [120000, 150000, 190000, 260000],
    evidence: [
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-06-14", content: "胡志明市首店探店视频中展示了本地供应链配送中心" },
      { brand: "蜜雪冰城 MIXUE", platform: "instagram", date: "2026-06-10", content: "东南亚负责人在IG连续两周定位胡志明市，分享本地食材市场考察照片" },
      { platform: "facebook", date: "2026-06-01", content: "蜜雪同时发布3个越南岗位：供应链经理、品控主管、冷链物流专员" },
    ],
    actionSuggestion: "蜜雪在越南同时招聘供应链、品控、冷链三岗，区别于其他品牌的轻资产出海模式",
  },

  // ═══ 原料/口味 · 补充 ═══
  {
    id: "ing-4",
    category: "ingredient",
    subCategory: "coffee_tea",
    title: "抹茶在北美TikTok从仪式感转向日常化应用",
    description: "抹茶内容在TikTok上的叙事正在从\"日式茶道仪式\"向\"日常饮品配方\"转变。抹茶拿铁、抹茶冰沙等快消化应用的内容占比从20%升至45%，预示抹茶正在从精品小众走向大众日常消费。",
    discussionVolume: 1600000,
    growthRate: 20,
    platforms: { tiktok: 68, instagram: 28, facebook: 4 },
    associatedBrands: [],
    competitorDensity: "low",
    weeklyVolumes: [260000, 330000, 450000, 560000],
    evidence: [
      { platform: "tiktok", date: "2026-06-12", content: "\"Matcha Latte at Home\"话题标签月均增长25%，内容以UGC家庭制作教程为主" },
      { platform: "instagram", date: "2026-06-08", content: "多家DTC抹茶品牌（Jade Leaf、MatchaBar）在IG投放高频生活方式内容" },
    ],
    actionSuggestion: "抹茶快消化应用（拿铁/冰沙）的内容占比从20%升至45%，精品小众→大众日常的转向明确",
  },
  {
    id: "ing-5",
    category: "ingredient",
    subCategory: "dairy",
    title: "植物基/燕麦奶的社媒品类教育完成，进入品牌竞争阶段",
    description: "燕麦奶在三个平台的讨论中，\"为什么要喝\"的品类教育内容减少，\"哪个牌子好喝\"的品牌对比内容增多——这是品类成熟期的标志。",
    discussionVolume: 2100000,
    growthRate: 12,
    platforms: { tiktok: 45, instagram: 40, facebook: 15 },
    associatedBrands: [],
    competitorDensity: "high",
    weeklyVolumes: [420000, 480000, 540000, 650000],
    evidence: [
      { platform: "tiktok", date: "2026-06-15", content: "\"Best Oat Milk Taste Test\"成为热门内容格式，多个KOL发布横向测评" },
      { platform: "instagram", date: "2026-06-10", content: "Oatly从\"教你用燕麦奶\"转向\"Barista Edition专业级\"品牌内容" },
    ],
    actionSuggestion: "Oatly等品牌从品类教育转向品牌差异化内容——品类教育窗口正在关闭，品牌竞争阶段开启",
  },

  // ═══ 品类赛道 · 补充 ═══
  {
    id: "cat-4",
    category: "category",
    subCategory: "coffee",
    title: "精品咖啡品牌在TikTok从\"第三空间\"转向\"内容媒体\"策略",
    description: "精品咖啡连锁（Blue Bottle、%Arabica、Manner等）的社媒策略正在从\"展示门店空间美学\"转向\"打造独立内容IP\"。产品研发过程、咖啡师个人IP、产区溯源系列成为新内容支柱。",
    discussionVolume: 1350000,
    growthRate: 28,
    platforms: { tiktok: 55, instagram: 35, facebook: 10 },
    associatedBrands: [],
    competitorDensity: "medium",
    weeklyVolumes: [220000, 280000, 380000, 470000],
    evidence: [
      { platform: "tiktok", date: "2026-06-14", content: "Blue Bottle\"Coffee Roaster Series\"内容系列在TikTok平均互动率是门店美学内容的2.3倍" },
      { platform: "instagram", date: "2026-06-08", content: "%Arabica咖啡师个人账号矩阵策略——每家首店搭配一个品牌咖啡师KOL" },
    ],
    actionSuggestion: "Blue Bottle的内容IP策略互动率是传统门店美学内容的2.3倍——精品咖啡行业的内容范式正在转变",
  },
  {
    id: "cat-5",
    category: "category",
    subCategory: "prepared_food",
    title: "预制菜/方便食品的社媒讨论从\"便利\"转向\"品质\"叙事",
    description: "Facebook食品群组中预制菜话题的讨论框架正在变化：2025年以\"省时间\"为核心叙事，2026年转向\"餐厅级品质在家做\"。消费者的品质预期正在提升。",
    discussionVolume: 950000,
    growthRate: 22,
    platforms: { tiktok: 30, instagram: 15, facebook: 55 },
    associatedBrands: [],
    competitorDensity: "medium",
    weeklyVolumes: [160000, 200000, 260000, 350000],
    evidence: [
      { platform: "facebook", date: "2026-06-13", content: "Facebook Group \"Home Cooking Made Easy\"中预制菜测评帖月均增长40%，成员超50万" },
      { platform: "tiktok", date: "2026-06-09", content: "预制菜品牌\"锅圈食汇\"的TikTok内容从\"方便火锅\"转向\"食材溯源+品质升级\"叙事" },
    ],
    actionSuggestion: "消费者对预制菜的期待从\"省时间\"向\"好吃+健康+方便\"三者并重升级，品质叙事占比上升",
  },

  // ═══ 区域市场 · 补充 ═══
  {
    id: "reg-3",
    category: "regional",
    subCategory: "europe",
    title: "英国/欧洲新茶饮从\"华人圈\"向\"主流消费\"渗透的早期信号",
    description: "伦敦、巴黎、柏林三个城市的茶饮相关TikTok内容中，非华人创作者的占比从2025年的15%升至2026年上半年的28%。伦敦TikTok美食榜中茶饮相关内容首次进入前20。渗透仍处早期但方向明确。",
    discussionVolume: 680000,
    growthRate: 38,
    platforms: { tiktok: 60, instagram: 30, facebook: 10 },
    associatedBrands: [],
    competitorDensity: "low",
    weeklyVolumes: [100000, 140000, 190000, 250000],
    evidence: [
      { platform: "tiktok", date: "2026-06-12", content: "英国本土TikTok美食KOL @londonfoodies 发布bubble tea探店系列，累计播放800万" },
      { platform: "instagram", date: "2026-06-05", content: "柏林新开的独立茶饮店通过IG Reels本地化内容获德文评论占比首次超50%" },
    ],
    actionSuggestion: "伦敦TikTok美食榜茶饮内容首次进入前20，非华人创作者贡献占比从15%升至28%",
  },
  {
    id: "reg-4",
    category: "regional",
    subCategory: "middle_east",
    title: "中东市场出现茶饮品牌的早期试探信号",
    description: "迪拜和利雅得的TikTok美食内容中，茶饮相关标签开始出现。中东年轻消费者对\"无酒精社交饮品\"的需求与茶饮品类天然契合——这是一个几乎零竞品的新兴市场。",
    discussionVolume: 420000,
    growthRate: 50,
    platforms: { tiktok: 70, instagram: 25, facebook: 5 },
    associatedBrands: [],
    competitorDensity: "low",
    weeklyVolumes: [55000, 80000, 130000, 155000],
    evidence: [
      { platform: "tiktok", date: "2026-06-10", content: "迪拜Mall茶饮快闪店探店视频在阿联酋TikTok美食榜进入前30，阿拉伯语评论占比高" },
      { platform: "instagram", date: "2026-06-03", content: "沙特美食KOL开始自发关注亚洲茶饮品牌，评论中\"什么时候来利雅得\"类提问频繁出现" },
    ],
    actionSuggestion: "迪拜Mall茶饮快闪内容进入阿联酋美食榜前30，沙特用户开始自发询问品牌何时进入当地",
  },

  // ═══ 竞品策略 · 补充 ═══
  {
    id: "str-3",
    category: "strategy",
    subCategory: "pricing",
    title: "头部品牌定价策略走向两极分化：下沉极致性价比 vs 海外品牌溢价",
    description: "品牌在国内和海外市场采取了截然相反的定价策略。国内下沉市场出现了\"9.9元咖啡\"的极致性价比竞争，而同一品牌在海外市场定价可达国内的2-3倍。",
    discussionVolume: 890000,
    growthRate: 18,
    platforms: { tiktok: 50, instagram: 30, facebook: 20 },
    associatedBrands: ["瑞幸 Luckin", "蜜雪冰城 MIXUE", "喜茶 HEYTEA"],
    competitorDensity: "high",
    weeklyVolumes: [160000, 200000, 260000, 270000],
    evidence: [
      { brand: "瑞幸 Luckin", platform: "instagram", date: "2026-05-28", content: "国内9.9元咖啡节如火如荼，新加坡门店定价为S$6.8（约¥35）" },
      { brand: "蜜雪冰城 MIXUE", platform: "tiktok", date: "2026-06-14", content: "越南定价约VND 35,000（约¥10），远高于国内定位但在当地仍属平价" },
      { brand: "喜茶 HEYTEA", platform: "instagram", date: "2026-05-20", content: "纽约门店定价约$7-9/杯（约¥50-65），为国内价格2-3倍" },
    ],
    actionSuggestion: "瑞幸国内9.9元→新加坡约¥35；喜茶国内¥20+→纽约约¥55——同一品牌海外定价为国内2-3倍",
  },
];
